title: Charbel-Raphaël Segerie # your name (or website title) here
logo: "/images/fairshot.png?raw=true" # your photo (or logo) here
description:
  >
  Executive Director, <a href="https://www.securite-ia.fr/">CeSIA</a><br>
  (French Center for AI Safety)<br><br>
  EU AI Act, GPAI Code of Practice Evaluator<br>
  OECD AI Expert<br><br>
  <a href="https://www.linkedin.com/in/charbel-raphael-segerie/">LinkedIn</a> &middot;
  <a href="https://twitter.com/CRSegerie">Twitter</a> &middot;
  <a href="https://scholar.google.com/citations?user=PLACEHOLDER">Scholar</a> &middot;
  <a href="https://github.com/crsegerie">GitHub</a>
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
baseurl:
url: https://crsegerie.github.io
