title: Charbel-Raphaël Segerie # your name (or website title) here
logo: "/images/photo_profil.jpg?raw=true" # your photo (or logo) here
description:
  > # your text below (remove <br> elements if you don't need line breaks)
I am currently the head of the AI Unit at <a href="https://www.effisciences.org/">EffiSciences</a>.
I am a former graduate of the <a href="http://math.ens-paris-saclay.fr/version-francaise/formations/master-mva/contenus-/master-mva-cours-161721.kjsp?RH=1409824973905">MVA Master's program</a> at <a href="https://fr.wikipedia.org/wiki/%C3%89cole_normale_sup%C3%A9rieure_Paris-Saclay">École Normale Supérieure Paris-Saclay</a>.
<br><br>
I work on AI safety, along with my students. I have organized and led the <a href="https://docs.google.com/document/d/1xxYPtgZlrBPNGS6aEFJAas0gFllQbN3iI0Nh3rDHdpU/edit?usp=sharing">Turing Seminar</a>, a course on AI safety in the MVA Master's program, and the bootcamps <a href="https://effisciences-research.notion.site/ML-for-Good-8b94525e6d98425083731a223b53b237">ML4Good</a>.
This site contains past student work. You can find <a href="https://www.lesswrong.com/users/charbel-raphael-segerie">here</a> more recent work on AI safety, which focuses on RLHF and interpretability.

I was previously the CTO of <a href="https://omniscience.academy/">Omnisciences</a>, which is now defunct :). I also conducted some research in neuroscience.
I have a penchant for philosophy and jazz piano.
<br><br>
Here is my <a href="https://www.linkedin.com/in/charbel-raphael-segerie/">LinkedIn</a>, <a href="https://twitter.com/CRSegerie">Twitter</a>, and <a href="https://github.com/crsegerie">Github</a> profiles.
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
baseurl:
url: http://crsegerie.github.io
