title: Charbel-Raphaël Segerie # your name (or website title) here
logo: "/images/photo_conf_waise.jpg?raw=true" # your photo (or logo) here
description:
  > # your text below (remove <br> elements if you don't need line breaks)
  I am currently the head of the AI Unit at <a href="https://ia.effisciences.org/">EffiSciences</a>.
  <br><br>
  I work mainly on AI safety. I have organized and led the <a href="https://www.master-mva.com/cours/seminaire-turing/">Turing Seminar</a>, a course on AI safety in the MVA Master's program, and the bootcamps <a href="https://effisciences-research.notion.site/ML-for-Good-8b94525e6d98425083731a223b53b237">ML4Good</a>.
  This site contains past student work. You can find <a href="https://www.lesswrong.com/users/charbel-raphael-segerie">here</a> more recent work on AI safety, which focuses on RLHF and interpretability.

  I was TA during <a href="https://www.arena.education/team">ARENA</a>, in <a href="https://www.cbai.ai/ml-bootcamp">Berkeley</a>, and CTO of <a href="https://omniscience.academy/">Omnisciences</a>, which is now defunct :). I've researched at Inria Parietal and Neurospin, and enjoy philosophy and jazz piano.
  <br><br>
  Here is my <a href="https://www.linkedin.com/in/charbel-raphael-segerie/">LinkedIn</a>, <a href="https://twitter.com/CRSegerie">Twitter</a>, and <a href="https://github.com/crsegerie">Github</a>.
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
baseurl:
url: http://crsegerie.github.io
